#!/usr/bin/env bash
#
# This scitpt will go through any mapped git sub modules and 
# initialise and pull the repository content.

# Initialise and pull any newly mapped git sub repositories
git submodule update --init --recursive

# Pull changes from any existing git sub repositories.
git submodule foreach git pull origin master
